export const LegacyApiRoutes = {
  download: "/api/download",
  search: "/api/search",
  skill: "/api/skill",
  skillResolve: "/api/skill/resolve",
  cliWhoami: "/api/cli/whoami",
  cliUploadUrl: "/api/cli/upload-url",
  cliPublish: "/api/cli/publish",
  cliTelemetryInstall: "/api/cli/telemetry/install",
  cliSkillDelete: "/api/cli/skill/delete",
  cliSkillUndelete: "/api/cli/skill/undelete",
} as const;

export const ApiRoutes = {
  search: "/api/v1/search",
  resolve: "/api/v1/resolve",
  download: "/api/v1/download",
  publishTokenMint: "/api/v1/publish/token/mint",
  skills: "/api/v1/skills",
  skillsSh: "/api/v1/skills-sh",
  skillScans: "/api/v1/skills/-/scan",
  packages: "/api/v1/packages",
  codePlugins: "/api/v1/code-plugins",
  bundlePlugins: "/api/v1/bundle-plugins",
  promotions: "/api/v1/promotions",
  stars: "/api/v1/stars",
  transfers: "/api/v1/transfers",
  publishers: "/api/v1/publishers",
  users: "/api/v1/users",
  contentRights: "/api/v1/content-rights",
  whoami: "/api/v1/whoami",
} as const;
