import { expect, test } from "@playwright/test";
import convexBrowser from "convex/browser";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import { expectHealthyPage, trackRuntimeErrors, waitForHydration } from "../helpers/runtimeErrors";
import { publishSkillVersion, signInAsLocalOwner } from "./helpers";

test.skip(
  process.env.VITE_ENABLE_DEV_AUTH !== "1",
  "local-auth lifecycle tests require the local dev auth runner",
);

const WORKER_TOKEN = process.env.SECURITY_SCAN_WORKER_TOKEN ?? "local-e2e-worker-token";
const { ConvexHttpClient } = convexBrowser;
type ConvexHttpClientInstance = InstanceType<typeof ConvexHttpClient>;

type ClaimedScanJob = {
  job: { _id: Id<"securityScanJobs">; leaseToken: string };
  target?: { skill?: { slug?: string }; version?: { version?: string } };
};

type ClaimedSkillCardJob = {
  job: { _id: Id<"skillCardGenerationJobs">; leaseToken: string };
  target?: { skill?: { slug?: string }; version?: { version?: string } };
};

function convexClient() {
  const convexUrl = process.env.VITE_CONVEX_URL;
  if (!convexUrl) throw new Error("VITE_CONVEX_URL is required");
  return new ConvexHttpClient(convexUrl);
}

function convexSiteUrl() {
  const url = process.env.VITE_CONVEX_SITE_URL;
  if (!url) throw new Error("VITE_CONVEX_SITE_URL is required");
  return url.replace(/\/$/u, "");
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

async function waitForClaimedScanJob(client: ConvexHttpClientInstance, slug: string) {
  const deadline = Date.now() + 20_000;
  while (Date.now() < deadline) {
    const jobs = (await client.action(api.securityScan.claimCodexScanJobs, {
      token: WORKER_TOKEN,
      workerId: `pw-skill-card-${slug}`,
      limit: 20,
      leaseMs: 60_000,
    })) as ClaimedScanJob[];
    const match = jobs.find((job) => job.target?.skill?.slug === slug);
    if (match) return match;
    await sleep(500);
  }
  throw new Error(`Timed out waiting for security scan job for ${slug}`);
}

async function waitForClaimedSkillCardJob(client: ConvexHttpClientInstance, slug: string) {
  const deadline = Date.now() + 20_000;
  while (Date.now() < deadline) {
    const jobs = (await client.action(api.skillCards.claimSkillCardJobs, {
      token: WORKER_TOKEN,
      workerId: `pw-skill-card-${slug}`,
      limit: 20,
      leaseMs: 60_000,
    })) as ClaimedSkillCardJob[];
    const match = jobs.find((job) => job.target?.skill?.slug === slug);
    if (match) return match;
    await sleep(500);
  }
  throw new Error(`Timed out waiting for Skill Card generation job for ${slug}`);
}

test("publishing a skill queues scan, queues skill-card generation, and shows the generated card", async ({
  page,
}, testInfo) => {
  const errors = trackRuntimeErrors(page);
  const client = convexClient();
  const slug = `pw-card-${Date.now().toString(36)}`;
  const displayName = "Playwright Skill Card Skill";

  const ownerHandle = await signInAsLocalOwner(page);
  await publishSkillVersion(page, testInfo, {
    ownerHandle,
    slug,
    displayName,
    version: "1.0.0",
    versionLabel: "skill card release",
    changelog: "Initial release for the generated Skill Card lifecycle.",
  });

  const scanJob = await waitForClaimedScanJob(client, slug);
  expect(scanJob.target?.version?.version).toBe("1.0.0");

  await client.action(api.securityScan.completeCodexScanJob, {
    token: WORKER_TOKEN,
    jobId: scanJob.job._id,
    leaseToken: scanJob.job.leaseToken,
    runId: "playwright-local-auth",
    llmAnalysis: {
      status: "clean",
      verdict: "benign",
      confidence: "high",
      summary: "No suspicious behavior in the local Playwright fixture.",
      guidance: "Fixture is safe for local e2e validation.",
      model: "mock-local-e2e",
      checkedAt: Date.now(),
    },
  });

  const cardJob = await waitForClaimedSkillCardJob(client, slug);
  expect(cardJob.target?.version?.version).toBe("1.0.0");

  const markdown = [
    "# Skill Card",
    "",
    `Skill: ${displayName}`,
    "",
    "Generated by the local Playwright worker harness.",
  ].join("\n");
  await client.action(api.skillCards.completeSkillCardJob, {
    token: WORKER_TOKEN,
    jobId: cardJob.job._id,
    leaseToken: cardJob.job.leaseToken,
    runId: "playwright-local-auth",
    markdown,
  });

  await page.reload({ waitUntil: "domcontentloaded" });
  await waitForHydration(page);
  const skillCardTab = page.getByRole("tab", { name: "Skill Card" });
  await skillCardTab.click();
  await expect(skillCardTab).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("heading", { name: "Skill Card", exact: true })).toBeVisible();
  await expect(page.getByText("Generated by the local Playwright worker harness.")).toBeVisible();

  const cardResponse = await page.request.get(`${convexSiteUrl()}/api/v1/skills/${slug}/card`);
  expect(cardResponse.status()).toBe(200);
  expect(await cardResponse.text()).toBe(markdown);

  await expectHealthyPage(page, errors);
});

test("skill publishers can create a skill and publish a new version", async ({
  page,
}, testInfo) => {
  const errors = trackRuntimeErrors(page);
  const slug = `pw-life-${Date.now().toString(36)}`;
  const displayName = "Playwright Lifecycle Skill";

  let ownerHandle = await signInAsLocalOwner(page);

  ownerHandle = await publishSkillVersion(page, testInfo, {
    ownerHandle,
    slug,
    displayName,
    version: "1.0.0",
    versionLabel: "first release",
    changelog: "Initial release from the browser publish flow.",
  });

  const metadata = page.locator(".sidebar-metadata");
  await expect(metadata.getByText("Current version", { exact: true })).toBeVisible();
  await expect(metadata.getByText("v1.0.0", { exact: true })).toBeVisible();

  await expect(page.getByRole("link", { name: "Settings" })).toBeVisible();
  await page.getByRole("link", { name: "New version" }).click();

  await expect(page).toHaveURL(/\/skills\/publish\?updateSlug=/);
  await expect(page.locator("#slug")).toHaveValue(slug);
  await expect(page.locator("#displayName")).toHaveValue(displayName);
  await expect(page.locator("#version")).toHaveValue("1.0.1");
  await expect(page.locator("#ownerHandle")).toHaveValue(ownerHandle);

  await publishSkillVersion(page, testInfo, {
    ownerHandle,
    slug,
    displayName,
    version: "1.0.1",
    versionLabel: "second release",
    changelog: "Second release published through the owner new-version workflow.",
  });

  await expect(metadata.getByText("Current version", { exact: true })).toBeVisible();
  await expect(metadata.getByText("v1.0.1", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Versions" }).click();
  await expect(page.getByRole("heading", { name: "Versions" })).toBeVisible();
  await expect(page.getByText(/^v1\.0\.1\b/).first()).toBeVisible();
  await expect(page.getByText(/^v1\.0\.0\b/).first()).toBeVisible();

  await expectHealthyPage(page, errors);
});
